version: "3.2"

services:
    nginx-ingress:
        image: docker-compose-ingress
        ports:
            - "8090:80"
        links:
            - static
            - docker-registry-nginx
            - api
        networks:
            - infrabox

    minio:
        image: minio/minio
        command: server /data
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        networks:
            - infrabox


    minio-init:
        image: $INFRABOX_DOCKER_REGISTRY/infrabox/docker-compose-minio-init
        networks:
            - infrabox

    docker-registry:
        image: registry
        networks:
            - infrabox


    docker-registry-auth:
        image: $INFRABOX_DOCKER_REGISTRY/infrabox/docker-registry-auth
        environment:
            - INFRABOX_SERVICE=registry-auth
            - INFRABOX_VERSION=latest
        links:
        networks:
            - infrabox
        volumes: []


    docker-registry-nginx:
        image: $INFRABOX_DOCKER_REGISTRY/infrabox/docker-registry-auth
        links:
            - docker-registry
            - docker-registry-auth
        environment:
            - INFRABOX_DOCKER_REGISTRY_ADMIN_PASSWORD=admin
            - INFRABOX_DOCKER_REGISTRY_ADMIN_USERNAME=admin
            - INFRABOX_AUTH_HOST=docker-registry-auth
            - INFRABOX_REGISTRY_HOST=docker-registry
        networks:
            - infrabox


    scheduler:
        image: $INFRABOX_DOCKER_REGISTRY/infrabox/scheduler/docker-compose
        tty: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/infrabox-compose/repo:/tmp/infrabox-compose/repo
        environment:
            - INFRABOX_SERVICE=scheduler
            - INFRABOX_VERSION=latest
            - INFRABOX_JOB_MAX_OUTPUT_SIZE=104857600
        links:
        networks:
            - infrabox

    static:
        image: $INFRABOX_DOCKER_REGISTRY/infrabox/static
        networks:
            - infrabox

    job-git:
        image: $INFRABOX_DOCKER_REGISTRY/infrabox/job-git
        environment:
            - INFRABOX_SERVICE=job-git
            - INFRABOX_VERSION=latest
            - INFRABOX_JOB_REPO_MOUNT_PATH=/tmp/infrabox-compose/repo
            - INFRABOX_GENERAL_DONT_CHECK_CERTIFICATES=true
        networks:
            - infrabox
        volumes:
            - /tmp/infrabox-compose/repo:/tmp/infrabox-compose/repo

    api:
        image: $INFRABOX_DOCKER_REGISTRY/infrabox/api
        environment:
            - INFRABOX_SERVICE=api
            - INFRABOX_VERSION=latest
            - INFRABOX_STORAGE_GCS_ENABLED=false
            - INFRABOX_STORAGE_S3_ENABLED=true
            - INFRABOX_STORAGE_S3_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - INFRABOX_STORAGE_S3_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - INFRABOX_STORAGE_S3_PORT=9000
            - INFRABOX_STORAGE_S3_ENDPOINT=minio
            - INFRABOX_STORAGE_S3_SECURE=false
            - INFRABOX_STORAGE_S3_REGION=us-east-1
            - INFRABOX_STORAGE_S3_BUCKET=infrabox
            - INFRABOX_GITHUB_ENABLED=false
            - INFRABOX_GITHUB_LOGIN_ENABLED=false
            - INFRABOX_GERRIT_ENABLED=false
            - INFRABOX_ACCOUNT_LDAP_ENABLED=false
            - INFRABOX_API_PORT=8080
            - INFRABOX_API_MONITORING_PORT=8080
            - INFRABOX_JOB_MAX_OUTPUT_SIZE=104857600
            - INFRABOX_JOB_SECURITY_CONTEXT_CAPABILITIES_ENABLED=false
            - INFRABOX_CLUSTER_NAME=master
        links:
            - minio
        networks:
            - infrabox
        volumes: []

networks:
    infrabox:
        driver: bridge
