{{ if .Values.scheduler.enabled }}
{{ if .Values.general.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrabox-fluentd
  namespace: infrabox-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: infrabox-fluentd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: infrabox-fluentd
  namespace: infrabox-system
---
{{ end }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: infrabox-fluentd
  namespace: infrabox-system
  labels:
    app: infrabox-fluentd-logging
    version: v1
spec:
  template:
    metadata:
      labels:
        app: infrabox-fluentd-logging
    spec:
      {{ if .Values.general.rbac.enabled }}
      serviceAccount: infrabox-fluentd
      serviceAccountName: infrabox-fluentd
      {{ end }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: infrabox-fluentd
        image: {{ required "general.docker_registry is required" .Values.general.docker_registry }}/{{ default "fluentd" .Values.fluentd.image }}:{{ required "fluentd.tag is required" .Values.fluentd.tag }}
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{ end }}
